name: symclf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - gmsh
  - ipywidgets
  - jax
  - jaxopt
  - jupyterlab
  - numpy
  - petsc4py
  - pygmo
  - pygraphviz
  - python-gmsh
  - pyvista
  - scikit-learn
  - scipy
  - trame
  - typeguard
  - yaml
  - mpc
  - pip:
      - pre-commit
      - pytest
      - black
      - flake8